channels:
  - conda-forge

dependencies:
  - python=3.11.5
  - pip=23.2.1
  - truststore=0.8.0
  - python-chromedriver-binary
  - pip:
    - robocorp==1.0.0
    - pathlib==1.0.1
    - openpyxl
    - cdifflib==1.2.6
    - selenium==4.13.0
    - webdriver_manager

