# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.11.5               # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - truststore=0.8.0 
  - firefox                 # https://anaconda.org/conda-forge/firefox
  - geckodriver  
  - selenium # Certifique-se de usar a versão apropriada do Selenium.
  - webdrivermanager      # https://github.com/sethmlarson/truststore/blob/main/CHANGELOG.md
  - pip:
    - rpaframework    # https://rpaframework.org/releasenotes.html
    - robocorp
 # Para instalar automaticamente o geckodriver.