channels:
  - conda-forge

dependencies:
  - python=3.11.5
  - pip=23.2.1
  - truststore=0.8.0
  - pip:
    - openpyxl==3.1.2
    - robotframework-seleniumlibrary==6.1.2
    - robocorp==1.0.0
    - rpaframework==27.3.0




